### ISSUE TITLE
Add-on URL

### ISSUE THREAD

**Issue by AirQuick** [oxygenxml/oxygenxml.xlsx.import#1]
Just wondering if this URL in README is correct:

> it can be installed as an add on (Oxygen Help menu->Install new add-on) from the location: https://raw.githubusercontent.com/wendellpiez/JATSKit/master/oXygenJATSframework.xml

**Comment by raducoravu** [comment]
Oops, thanks, copy-pasta error, I changed the readme to point to the actual add-on location:

https://raw.githubusercontent.com/oxygenxml/oxygenxml.xlsx.import/master/addon.xml
